#!/usr/bin/env python3
"""
seed_db.py — populate the SQLite database with the original JLPT N4 question bank.

Usage:
    python seed_db.py                    # writes to /tmp/jlpt.db  (default)
    DB_PATH=./dev.db python seed_db.py   # custom path
"""
import json, os, sys

# allow running from project root without installing the package
sys.path.insert(0, os.path.dirname(__file__))
os.environ.setdefault("DB_PATH", "/tmp/jlpt.db")

from api.database import init_db, get_db

QUESTIONS = [
  {"id":"k001","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"きのう 友だちと 【映画】 を 見ました。","furigana":"きのう ともだちと えいが を みました。","choices":["えいが","えいか","えが","えいかく"],"answer":0,"explanation":"映画 dibaca えいが (film). 映=えい, 画=が. Pilihan えいか salah karena 画 di sini bersuara (が). えが kehilangan vokal panjang えい. えいかく bukan kata yang ada.","translation":"Kemarin saya menonton film bersama teman."},
  {"id":"k002","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"ねつが あるので 【病院】 へ 行きます。","furigana":"ねつが あるので びょういん へ いきます。","choices":["びょういん","びよういん","びょうい","びょいん"],"answer":0,"explanation":"病院 dibaca びょういん (rumah sakit). Perhatikan よう dengan ょ kecil dan vokal panjang. びよういん memakai よ besar (salah), びょうい dan びょいん kekurangan mora.","translation":"Karena demam, saya pergi ke rumah sakit."},
  {"id":"k003","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"来月 家族と 【旅行】 します。","furigana":"らいげつ かぞくと りょこう します。","choices":["りょこう","りょこお","りこう","りょうこう"],"answer":0,"explanation":"旅行 dibaca りょこう (perjalanan/wisata). 旅=りょ, 行=こう. りょこお salah menulis vokal panjang. りこう hilang ょ kecil. りょうこう menambah vokal panjang yang salah.","translation":"Bulan depan saya akan berwisata bersama keluarga."},
  {"id":"k004","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"田中さんは とても 【親切】 な 人です。","furigana":"たなかさんは とても しんせつ な ひとです。","choices":["しんせつ","しんせち","おやせつ","しんぜつ"],"answer":0,"explanation":"親切 dibaca しんせつ (baik hati). 親=しん (on'yomi), 切=せつ. おやせつ salah karena memakai kun'yomi おや. しんぜつ salah menambah suara dakuten pada せつ.","translation":"Tanaka-san adalah orang yang sangat baik hati."},
  {"id":"k005","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"駅の 前で 【地図】 を 見ました。","furigana":"えきの まえで ちず を みました。","choices":["ちず","じず","ちと","ちうず"],"answer":0,"explanation":"地図 dibaca ちず (peta). 地=ち, 図=ず. じず salah membaca 地 sebagai じ. ちと salah pada 図. ちうず menambah mora yang tidak ada.","translation":"Saya melihat peta di depan stasiun."},
  {"id":"k006","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"お金を 【銀行】 に 預けます。","furigana":"おかねを ぎんこう に あずけます。","choices":["ぎんこう","ぎんこお","きんこう","ぎんごう"],"answer":0,"explanation":"銀行 dibaca ぎんこう (bank). 銀=ぎん, 行=こう. ぎんこお salah tulis vokal panjang. きんこう salah karena 銀 harus ぎん. ぎんごう salah dakuten.","translation":"Saya menabung uang di bank."},
  {"id":"k007","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"来週 日本語の 【試験】 が あります。","furigana":"らいしゅう にほんごの しけん が あります。","choices":["しけん","じけん","しげん","けいけん"],"answer":0,"explanation":"試験 dibaca しけん (ujian). じけん (事件), しげん (資源), けいけん (経験) semua kata nyata yang mirip bunyi.","translation":"Minggu depan ada ujian bahasa Jepang."},
  {"id":"k008","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"あした 【都合】 が 悪いので 行けません。","furigana":"あした つごう が わるいので いけません。","choices":["つごう","とごう","つあい","つごお"],"answer":0,"explanation":"都合 dibaca つごう. 都=つ, 合=ごう. とごう salah baca 都. つあい salah baca 合. つごお salah tulis vokal panjang.","translation":"Besok kondisi saya tidak memungkinkan, jadi tidak bisa pergi."},
  {"id":"k009","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"母は いつも 六時に 家へ 【帰る】。","furigana":"ははは いつも ろくじに いえへ かえる。","choices":["かえる","かえす","もどる","きえる"],"answer":0,"explanation":"帰る dibaca かえる (pulang). かえす (返す), もどる (戻る), きえる (消える) makna berbeda.","translation":"Ibu selalu pulang ke rumah jam enam."},
  {"id":"k010","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"大学の 【試験】 を 【受ける】 つもりです。","furigana":"だいがくの しけんを うける つもりです。","choices":["うける","あける","うかる","さずける"],"answer":0,"explanation":"受ける dibaca うける (mengikuti ujian). あける (開ける), うかる (受かる), さずける (授ける) kanji/arti berbeda.","translation":"Saya berniat mengikuti ujian masuk universitas."},
  {"id":"trv01-k02","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"ホテルから 【景色】 が よく 見えます。","furigana":"ホテルから けしき が よく みえます。","choices":["けしき","かしき","けいしょく","げしき"],"answer":0,"explanation":"景色 dibaca けしき (pemandangan). Pilihan lain bukan bacaan yang benar.","translation":"Pemandangan terlihat jelas dari hotel."},
  {"id":"shp02-k01","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"スーパーで 【野菜】 を 買いました。","furigana":"スーパーで やさい を かいました。","choices":["やさい","やしゃい","のうさい","やすい"],"answer":0,"explanation":"野菜 dibaca やさい (sayuran).","translation":"Saya membeli sayuran di supermarket."},
  {"id":"shp02-k02","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"毎日 【朝】 6時に 起きます。","furigana":"まいにち あさ ろくじに おきます。","choices":["あさ","あした","ひる","よる"],"answer":0,"explanation":"朝 dibaca あさ (pagi).","translation":"Setiap hari saya bangun jam 6 pagi."},
  {"id":"shp02-k03","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"【季節】 ごとに 着る 服を 変えます。","furigana":"きせつ ごとに きる ふくを かえます。","choices":["きせつ","きしゃつ","きせい","きせき"],"answer":0,"explanation":"季節 dibaca きせつ (musim).","translation":"Saya mengganti pakaian sesuai dengan setiap musim."},
  {"id":"9m4k-k02","section":"kanji","level":"N4","instruction":"＿＿の ことばは ひらがなで どう かきますか。","passage":"","question":"毎日 学校に 【通う】 のは 大変です。","furigana":"まいにち がっこうに かよう のは たいへんです。","choices":["かよう","つうう","とおう","かいう"],"answer":0,"explanation":"通う dibaca かよう (pergi rutin).","translation":"Pergi ke sekolah setiap hari itu melelahkan."},
  {"id":"r001","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"駅で 友だちに 【あう】。","furigana":"えきで ともだちに あう。","choices":["会う","合う","回う","今う"],"answer":0,"explanation":"友だちにあう = bertemu teman → 会う. 合う (cocok) bunyi sama tapi beda makna.","translation":"Bertemu teman di stasiun."},
  {"id":"r002","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"コップに 【みず】 を 入れます。","furigana":"コップに みず を いれます。","choices":["水","氷","永","木"],"answer":0,"explanation":"みず = air → 水. 氷 (es), 永 (abadi), 木 (pohon).","translation":"Memasukkan air ke dalam gelas."},
  {"id":"r003","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"毎日 【でんしゃ】 で 会社へ 行きます。","furigana":"まいにち でんしゃ で かいしゃへ いきます。","choices":["電車","雷車","電者","雪車"],"answer":0,"explanation":"でんしゃ = kereta → 電車.","translation":"Setiap hari saya pergi ke kantor naik kereta."},
  {"id":"r004","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"朝ごはんを 【たべる】 時間が ありません。","furigana":"あさごはんを たべる じかんが ありません。","choices":["食べる","飲べる","飯べる","食る"],"answer":0,"explanation":"たべる = makan → 食べる.","translation":"Tidak ada waktu untuk makan sarapan."},
  {"id":"r005","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"デパートで 【あたらしい】 くつを 買いました。","furigana":"デパートで あたらしい くつを かいました。","choices":["新しい","親しい","辛しい","薪しい"],"answer":0,"explanation":"あたらしい = baru → 新しい.","translation":"Saya membeli sepatu baru di department store."},
  {"id":"r006","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"かぜを ひいて 学校を 【やすむ】。","furigana":"かぜを ひいて がっこうを やすむ。","choices":["休む","体む","休すむ","体すむ"],"answer":0,"explanation":"やすむ = istirahat → 休む.","translation":"Saya absen sekolah karena masuk angin."},
  {"id":"r007","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"私の 家は 駅から 【ちかい】 です。","furigana":"わたしの いえは えきから ちかい です。","choices":["近い","遠い","返い","折い"],"answer":0,"explanation":"ちかい = dekat → 近い. 遠い (jauh) adalah lawan kata.","translation":"Rumah saya dekat dari stasiun."},
  {"id":"r008","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"今日は 何【ようび】 ですか。","furigana":"きょうは なんようび ですか。","choices":["曜日","曜目","躍日","昭日"],"answer":0,"explanation":"ようび = hari dalam seminggu → 曜日.","translation":"Hari ini hari apa?"},
  {"id":"r009","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"毎日 【かんじ】 を 書く 練習を します。","furigana":"まいにち かんじ を かく れんしゅうを します。","choices":["漢字","感字","漢学","漢宇"],"answer":0,"explanation":"かんじ = huruf kanji → 漢字.","translation":"Setiap hari saya berlatih menulis kanji."},
  {"id":"r010","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"旅行で 【しゃしん】 を たくさん とりました。","furigana":"りょこうで しゃしん を たくさん とりました。","choices":["写真","写直","与真","写其"],"answer":0,"explanation":"しゃしん = foto → 写真.","translation":"Saya mengambil banyak foto saat berwisata."},
  {"id":"trv01-r01","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"友だちは 【ひこうき】 で アメリカへ 行きました。","furigana":"ともだちは ひこうき で アメリカへ いきました。","choices":["飛行機","飛上機","飛行気","飛行地"],"answer":0,"explanation":"ひこうき = pesawat → 飛行機.","translation":"Teman saya pergi ke Amerika dengan pesawat."},
  {"id":"trv01-r02","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"旅行中に 駅で 【あんない】 を もらいました。","furigana":"りょこうちゅうに えきで あんない を もらいました。","choices":["案内","案外","安内","案在"],"answer":0,"explanation":"あんない = panduan → 案内.","translation":"Saat perjalanan saya menerima panduan di stasiun."},
  {"id":"shp02-r01","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"電話 【ばんごう】 を 教えて ください。","furigana":"でんわ ばんごう を おしえて ください。","choices":["番号","番語","番合","番后"],"answer":0,"explanation":"ばんごう = nomor → 番号.","translation":"Tolong beri tahu nomor teleponnya."},
  {"id":"shp02-r02","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"この 店の 【りょうり】 は おいしいです。","furigana":"このみせの りょうり は おいしいです。","choices":["料理","良理","療理","領理"],"answer":0,"explanation":"りょうり = masakan → 料理.","translation":"Masakan di toko ini enak."},
  {"id":"shp02-r03","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"この おかしは 【ちゅうがっこう】 の とき よく 食べました。","furigana":"このおかしは ちゅうがっこう の とき よく たべました。","choices":["中学校","仲学校","中楽校","中額校"],"answer":0,"explanation":"ちゅうがっこう = SMP → 中学校.","translation":"Kue ini sering saya makan ketika SMP."},
  {"id":"9m4k-r01","section":"kanji_reverse","level":"N4","instruction":"＿＿の ことばは どの かんじを かきますか。","passage":"","question":"今日は ホテルに 【とまる】。","furigana":"きょうは ホテルに とまる。","choices":["泊まる","止まる","泊る","停まる"],"answer":0,"explanation":"とまる (menginap) → 泊まる. 止まる/停まる = berhenti.","translation":"Hari ini saya menginap di hotel."},
  {"id":"g001","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"私は 日本へ 行った （　　） が あります。","furigana":"わたしは にほんへ いった ____ が あります。","choices":["こと","もの","ところ","ばかり"],"answer":0,"explanation":"Pola 〜たことがある = pernah. 行ったことがある = pernah pergi.","translation":"Saya pernah pergi ke Jepang."},
  {"id":"g002","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"へやの 中 （　　） ねこが います。","furigana":"へやの なか ____ ねこが います。","choices":["に","で","を","へ"],"answer":0,"explanation":"Partikel に menunjukkan lokasi keberadaan dengan います/あります.","translation":"Ada kucing di dalam kamar."},
  {"id":"g003","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"音楽を 聞き （　　） 、勉強します。","furigana":"おんがくを きき ____ 、べんきょうします。","choices":["ながら","たり","ので","まで"],"answer":0,"explanation":"V-ます stem + ながら = sambil melakukan dua hal sekaligus.","translation":"Saya belajar sambil mendengarkan musik."},
  {"id":"g004","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"あした 早く 起き （　　） 。","furigana":"あした はやく おき ____ 。","choices":["なければなりません","なくてもいいです","ないでください","たいです"],"answer":0,"explanation":"〜なければなりません = harus.","translation":"Besok saya harus bangun pagi."},
  {"id":"g005","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"私は 友だちに 本を かして （　　） 。","furigana":"わたしは ともだちに ほんを かして ____ 。","choices":["もらいました","あげました","くれました","おきました"],"answer":0,"explanation":"〜てもらう = subjek menerima bantuan. 友だちにかしてもらいました = dipinjami buku.","translation":"Saya dipinjami buku oleh teman."},
  {"id":"g006","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"私は 夏休みに 国へ 帰る （　　） です。","furigana":"わたしは なつやすみに くにへ かえる ____ です。","choices":["つもり","ばかり","ところ","らしい"],"answer":0,"explanation":"〜つもりです = berniat/berencana.","translation":"Saya berniat pulang ke kampung halaman saat libur musim panas."},
  {"id":"g007","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"雨が 降っ （　　） 、試合を します。","furigana":"あめが ふっ ____ 、しあいを します。","choices":["ても","たら","ので","から"],"answer":0,"explanation":"〜ても = meskipun. 降っても試合をします = meski hujan tetap bertanding.","translation":"Meskipun hujan, pertandingan tetap dilakukan."},
  {"id":"g008","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"私は 先生 （　　） ほめられました。","furigana":"わたしは せんせい ____ ほめられました。","choices":["に","を","が","で"],"answer":0,"explanation":"Dalam kalimat pasif, pelaku ditandai partikel に. 先生にほめられました = dipuji oleh guru.","translation":"Saya dipuji oleh guru."},
  {"id":"g009","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"天気よほうに よると、あした 雨が 降る （　　） です。","furigana":"てんきよほうに よると、あした あめが ふる ____ です。","choices":["そう","よう","つもり","はず"],"answer":0,"explanation":"〜によると〜そうだ = menurut ~, katanya (伝聞).","translation":"Menurut ramalan cuaca, katanya besok akan hujan."},
  {"id":"g010","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"薬を 飲んだ （　　） 、なかなか なおりません。","furigana":"くすりを のんだ ____ 、なかなか なおりません。","choices":["のに","ので","から","ために"],"answer":0,"explanation":"〜のに = padahal. 飲んだのに治らない = padahal sudah minum obat tapi tak sembuh.","translation":"Padahal sudah minum obat, tetap tidak kunjung sembuh."},
  {"id":"shp02-g01","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"このセーターは 高い （　　） 、買いません。","furigana":"このセーターは たかい ____ 、かいません。","choices":["ので","のに","たら","でも"],"answer":0,"explanation":"〜ので = karena. 高いので買いません = karena mahal, tidak beli.","translation":"Karena sweter ini mahal, saya tidak membelinya."},
  {"id":"shp02-g02","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"私は 一度も すしを （　　） ことが ありません。","furigana":"わたしは いちども すしを ____ ことが ありません。","choices":["食べた","食べる","食べて","食べ"],"answer":0,"explanation":"Pola 〜たことがある/ない memakai bentuk lampau (た).","translation":"Saya belum pernah sekali pun makan sushi."},
  {"id":"sch03-g01","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"天気が 悪い （　　） 、学校へ 行きます。","furigana":"てんきが わるい ____ 、がっこうへ いきます。","choices":["のに","から","ので","ため"],"answer":0,"explanation":"〜のに = padahal/meskipun.","translation":"Padahal cuacanya buruk, saya tetap pergi ke sekolah."},
  {"id":"sch03-g02","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"宿題を （　　） から、寝ます。","furigana":"しゅくだいを ____ から、ねます。","choices":["した","する","しない","して"],"answer":0,"explanation":"〜たから = karena sudah. 宿題をしたから寝ます = karena sudah PR lalu tidur.","translation":"Karena sudah mengerjakan PR, saya tidur."},
  {"id":"9m4k-g01","section":"bunpou","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"私は 毎日 6時 （　　） 起きます。","furigana":"わたしは まいにち ろくじ ____ おきます。","choices":["に","で","が","を"],"answer":0,"explanation":"Partikel に menandai titik waktu tertentu.","translation":"Saya bangun jam 6 setiap hari."},
  {"id":"v001","section":"kotoba","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"たくさん 歩いたので、足が （　　） です。","furigana":"たくさん あるいたので、あしが ____ です。","choices":["いたい","おいしい","あかるい","しずか"],"answer":0,"explanation":"Banyak berjalan → kaki sakit (いたい).","translation":"Karena banyak berjalan, kaki saya sakit."},
  {"id":"v002","section":"kotoba","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"のどが かわいたので、何か （　　） です。","furigana":"のどが かわいたので、なにか ____ です。","choices":["飲みたい","食べたい","見たい","聞きたい"],"answer":0,"explanation":"のどがかわく = haus → ingin minum (飲みたい).","translation":"Karena haus, saya ingin minum sesuatu."},
  {"id":"v003","section":"kotoba","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"部屋が くらいので、電気を （　　） 。","furigana":"へやが くらいので、でんきを ____ 。","choices":["つけます","けします","しめます","あけます"],"answer":0,"explanation":"Kamar gelap → menyalakan lampu (電気をつける).","translation":"Karena kamar gelap, saya menyalakan lampu."},
  {"id":"v004","section":"kotoba","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"土曜日に 友だちと 映画を 見る （　　） を しました。","furigana":"どようびに ともだちと えいがを みる ____ を しました。","choices":["やくそく","しゅくだい","そうじ","しつもん"],"answer":0,"explanation":"約束をする = membuat janji.","translation":"Saya berjanji untuk menonton film dengan teman pada hari Sabtu."},
  {"id":"v005","section":"kotoba","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"この みせの 料理は とても （　　） です。","furigana":"この みせの りょうりは とても ____ です。","choices":["おいしい","つまらない","むずかしい","うれしい"],"answer":0,"explanation":"料理 → rasa: おいしい (enak).","translation":"Masakan di toko ini sangat enak."},
  {"id":"v006","section":"kotoba","level":"N4","instruction":"＿＿の ことばに いみが いちばん ちかい ものを えらんで ください。","passage":"","question":"父は 【ときどき】 りょうりを します。","furigana":"ちちは ときどき りょうりを します。","choices":["たまに","いつも","まいにち","ぜんぜん"],"answer":0,"explanation":"ときどき ≈ たまに (kadang-kadang).","translation":"Ayah kadang-kadang memasak."},
  {"id":"v007","section":"kotoba","level":"N4","instruction":"＿＿の ことばに いみが いちばん ちかい ものを えらんで ください。","passage":"","question":"あの 人は とても 【ゆうめい】 です。","furigana":"あの ひとは とても ゆうめい です。","choices":["みんなが しって います","おかねが あります","しんせつです","げんきです"],"answer":0,"explanation":"有名 (terkenal) ≈ みんなが知っています.","translation":"Orang itu sangat terkenal."},
  {"id":"v008","section":"kotoba","level":"N4","instruction":"＿＿の ことばに いみが いちばん ちかい ものを えらんで ください。","passage":"","question":"しごとが やっと 【おわりました】 。","furigana":"しごとが やっと おわりました。","choices":["すみました","はじまりました","つづきました","やすみました"],"answer":0,"explanation":"終わる ≈ 済む (selesai).","translation":"Pekerjaan akhirnya selesai."},
  {"id":"v009","section":"kotoba","level":"N4","instruction":"＿＿の ことばに いみが いちばん ちかい ものを えらんで ください。","passage":"","question":"この かばんは とても 【じょうぶ】 です。","furigana":"この かばんは とても じょうぶ です。","choices":["こわれにくいです","かるいです","たかいです","あたらしいです"],"answer":0,"explanation":"丈夫 ≈ こわれにくい (tidak mudah rusak).","translation":"Tas ini sangat kuat/awet."},
  {"id":"v010","section":"kotoba","level":"N4","instruction":"＿＿の ことばに いみが いちばん ちかい ものを えらんで ください。","passage":"","question":"へやを きれいに 【かたづけました】 。","furigana":"へやを きれいに かたづけました。","choices":["せいりしました","よごしました","ひろげました","かざりました"],"answer":0,"explanation":"片づける ≈ 整理する (merapikan).","translation":"Saya merapikan kamar hingga bersih."},
  {"id":"v011","section":"kotoba","level":"N4","instruction":"つぎの ことばの つかいかたで いちばん いい ものを えらんで ください。 ── しゅうかん（習慣）","passage":"","question":"「しゅうかん」を 正しく つかって いる ぶんを えらんで ください。","furigana":"","choices":["毎朝 さんぽするのが 私の 習慣です。","コーヒーを 習慣しました。","きれいな 習慣ですね。","習慣へ あそびに 行きます。"],"answer":0,"explanation":"習慣 = kebiasaan (kata benda). 〜は私の習慣です adalah pemakaian benar.","translation":"Berjalan-jalan setiap pagi adalah kebiasaan saya."},
  {"id":"v012","section":"kotoba","level":"N4","instruction":"つぎの ことばの つかいかたで いちばん いい ものを えらんで ください。 ── あんぜん（安全）","passage":"","question":"「あんぜん」を 正しく つかって いる ぶんを えらんで ください。","furigana":"","choices":["この みちは くるまが すくなくて 安全です。","今日は 安全な てんきです。","ごはんを 安全しました。","安全を のみました。"],"answer":0,"explanation":"安全 = aman (kata sifat-na). 'みちが安全' adalah pemakaian benar.","translation":"Jalan ini aman karena sedikit kendaraan."},
  {"id":"v013","section":"kotoba","level":"N4","instruction":"つぎの ことばの つかいかたで いちばん いい ものを えらんで ください。 ── しらべる（調べる）","passage":"","question":"「しらべる」を 正しく つかって いる ぶんを えらんで ください。","furigana":"","choices":["わからない ことばを じしょで 調べます。","あさ はやく 調べました。","ともだちと こうえんで 調べます。","みずを 調べて のみます。"],"answer":0,"explanation":"調べる = memeriksa/mencari. Mencari kata di kamus adalah pemakaian benar.","translation":"Saya mencari kata yang tidak dimengerti di kamus."},
  {"id":"v014","section":"kotoba","level":"N4","instruction":"つぎの ことばの つかいかたで いちばん いい ものを えらんで ください。 ── ひつよう（必要）","passage":"","question":"「ひつよう」を 正しく つかって いる ぶんを えらんで ください。","furigana":"","choices":["かいがい旅行には パスポートが 必要です。","今日は 必要が さむいです。","必要に がっこうへ 行きます。","ごはんを 必要しました。"],"answer":0,"explanation":"必要 = perlu. 'Aが必要です' adalah pemakaian benar.","translation":"Untuk perjalanan ke luar negeri, paspor diperlukan."},
  {"id":"v015","section":"kotoba","level":"N4","instruction":"（　　）に 何を 入れますか。いちばん いい ものを えらんで ください。","passage":"","question":"テストの 前に、しっかり （　　） して ください。","furigana":"テストの まえに、しっかり ____ して ください。","choices":["じゅんび","さんぽ","しょうかい","しつもん"],"answer":0,"explanation":"準備する = mempersiapkan. Sebelum tes harus 準備.","translation":"Sebelum tes, tolong persiapkan dengan baik."},
  {"id":"trv01-v01","section":"kotoba","level":"N4","instruction":"＿＿の ことばに いみが いちばん ちかい ものを えらんで ください。","passage":"","question":"旅行の 【計画】 を 立てるのは 楽しいです。","furigana":"りょこうの けいかく を たてるのは たのしいです。","choices":["プラン","方法","目的","気分"],"answer":0,"explanation":"計画 (rencana) ≈ プラン (plan).","translation":"Menyusun rencana perjalanan itu menyenangkan."},
  {"id":"sch03-v01","section":"kotoba","level":"N4","instruction":"（　　）に 入る ことばを えらんで ください。","passage":"","question":"天気が いいから、外で （　　） 。","furigana":"てんきが いいから、そとで ____ 。","choices":["遊びます","勉強します","寝ます","洗います"],"answer":0,"explanation":"Cuaca bagus → bermain di luar (遊びます).","translation":"Karena cuacanya bagus, saya bermain di luar."},
  {"id":"sch03-v02","section":"kotoba","level":"N4","instruction":"（　　）に 入る ことばを えらんで ください。","passage":"","question":"雨が ふるから、傘を （　　） ください。","furigana":"あめが ふるから、かさを ____ ください。","choices":["持って","作って","売って","かりて"],"answer":0,"explanation":"傘を持ってください = tolong bawa payung.","translation":"Karena akan hujan, tolong bawa payung."},
  {"id":"9m4k-v01","section":"kotoba","level":"N4","instruction":"（　　）に 入る ことばを えらんで ください。","passage":"","question":"友だちに 手紙を （　　） 。","furigana":"ともだちに てがみを ____ 。","choices":["送りました","通りました","曲がりました","止まりました"],"answer":0,"explanation":"手紙を送る = mengirim surat.","translation":"Saya mengirim surat kepada teman."},
  {"id":"9m4k-v02","section":"kotoba","level":"N4","instruction":"（　　）に 入る ことばを えらんで ください。","passage":"","question":"夏休みに 家族と 【　　】 へ 行きました。","furigana":"なつやすみに かぞくと ____ へ いきました。","choices":["海","橋","窓","机"],"answer":0,"explanation":"Libur musim panas → pergi ke 海 (laut/pantai).","translation":"Saat libur musim panas saya pergi ke pantai bersama keluarga."},
  {"id":"d001","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"田中(たなか)さん、お元気(げんき)ですか。私(わたし)は先週(せんしゅう)、大学(だいがく)の近(ちか)くに引(ひ)っ越(こ)しました。前(まえ)のアパートから大学までは、電車(でんしゃ)とバスで一時間半(いちじかんはん)もかかりました。でも、今(いま)のアパートは大学まで歩(ある)いて十分(じゅっぷん)ぐらいです。少(すこ)し狭(せま)いですが、新(あたら)しくてきれいです。","question":"今の アパートから 大学まで、どのくらい かかりますか。","furigana":"","choices":["歩いて 十分ぐらい","電車とバスで 一時間半","歩いて 一時間半","電車で 十分"],"answer":0,"explanation":"Teks: '今のアパートは大学まで歩いて十分ぐらい'. Satu setengah jam adalah jarak dari apartemen LAMA.","translation":"Tanaka-san, apa kabar? Minggu lalu saya pindah ke dekat kampus. Dari apartemen lama butuh 1,5 jam. Sekarang hanya 10 menit jalan kaki. Agak sempit tapi baru dan bersih."},
  {"id":"d002","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"田中(たなか)さん、お元気(げんき)ですか。私(わたし)は先週(せんしゅう)、大学(だいがく)の近(ちか)くに引(ひ)っ越(こ)しました。前(まえ)のアパートから大学までは、電車(でんしゃ)とバスで一時間半(いちじかんはん)もかかりました。でも、今(いま)のアパートは大学まで歩(ある)いて十分(じゅっぷん)ぐらいです。少(すこ)し狭(せま)いですが、新(あたら)しくてきれいです。","question":"今の アパートに ついて、正しい ものは どれですか。","furigana":"","choices":["狭いが、新しくて きれいだ","広くて 古い","大学から 遠い","電車で 通う"],"answer":0,"explanation":"Teks: '少し狭いですが、新しくてきれいです'.","translation":"Tanaka-san, apa kabar? Apartemen sekarang dekat kampus, agak sempit tapi baru dan bersih."},
  {"id":"d003","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"図書館(としょかん)からの お知(し)らせです。図書館は、毎週(まいしゅう)月曜日(げつようび)は お休(やす)みです。本(ほん)を借(か)りることが できるのは、一人(ひとり) 五冊(ごさつ)までです。借りた本は、二週間(にしゅうかん)で 返(かえ)して ください。","question":"図書館が 休みなのは いつですか。","furigana":"","choices":["月曜日","日曜日","土曜日","火曜日"],"answer":0,"explanation":"Teks: '毎週月曜日はお休みです'.","translation":"Perpustakaan tutup setiap Senin. Maksimal 5 buku, dikembalikan dalam 2 minggu."},
  {"id":"d004","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"図書館(としょかん)からの お知(し)らせです。図書館は、毎週(まいしゅう)月曜日(げつようび)は お休(やす)みです。本(ほん)を借(か)りることが できるのは、一人(ひとり) 五冊(ごさつ)までです。借りた本は、二週間(にしゅうかん)で 返(かえ)して ください。","question":"一人で 何冊まで 本を 借りる ことが できますか。","furigana":"","choices":["五冊","二冊","十冊","一冊"],"answer":0,"explanation":"Teks: '一人五冊までです'. 二週間 adalah lama peminjaman, bukan jumlah.","translation":"Perpustakaan tutup setiap Senin. Maksimal 5 buku, dikembalikan dalam 2 minggu."},
  {"id":"d005","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"山田(やまだ)さんは 毎朝(まいあさ) 六時(ろくじ)に 起(お)きて、近(ちか)くの 公園(こうえん)を 走(はし)ります。雨(あめ)の 日(ひ)は 走りませんが、その かわりに 家(いえ)で ヨガを します。山田さんは 「体(からだ)を 動(うご)かすと、一日(いちにち) 元気(げんき)に すごせます」と 言(い)って います。","question":"雨の 日に 山田さんは 何を しますか。","furigana":"","choices":["家で ヨガを する","公園を 走る","六時に 起きない","何も しない"],"answer":0,"explanation":"Teks: '雨の日は走りませんが、そのかわりに家でヨガをします'.","translation":"Yamada-san bangun jam 6 dan berlari di taman. Saat hujan, ia melakukan yoga di rumah."},
  {"id":"trv01-d01","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"夏休(なつやす)みに 家族(かぞく)で 京都(きょうと)へ 旅行(りょこう)に 行(い)きました。京都には 古(ふる)い お寺(てら)が たくさん あります。毎日(まいにち) ちがう お寺を 見(み)に 行きました。いちばん 楽(たの)しかったのは、お寺から 見えた 景色(けしき)です。","question":"この 人が いちばん 楽しかったのは 何ですか。","furigana":"","choices":["お寺から 見えた 景色","古い お寺の 数","毎日 お寺へ 行くこと","家族と 話すこと"],"answer":0,"explanation":"Teks: 'いちばん楽しかったのは、お寺から見えた景色です'.","translation":"Liburan musim panas ke Kyoto. Yang paling menyenangkan adalah pemandangan dari kuil."},
  {"id":"trv01-d02","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"私(わたし)たちは 毎年(まいとし) 同(おな)じ 田舎(いなか)へ 旅行(りょこう)に 行(い)きます。そこには 大(おお)きい 川(かわ)と 山(やま)が あります。夏(なつ)は 川で 泳(およ)ぎます。冬(ふゆ)は スキーを します。","question":"冬は 何を しますか。","furigana":"","choices":["スキーを します","川で 泳ぎます","旅行を やめます","山に 登ります"],"answer":0,"explanation":"Teks: '冬はスキーをします'.","translation":"Setiap tahun wisata ke desa. Musim panas berenang, musim dingin bermain ski."},
  {"id":"shp02-d01","section":"reading","level":"N4","instruction":"つぎの 文章を 読んで、しつもんに こたえて ください。","passage":"私(わたし)は 毎週(まいしゅう) 金曜日(きんようび)に 買(か)い物(もの)に 行(い)きます。スーパーで 野菜(やさい)や 肉(にく)、魚(さかな)を 買います。それから 本屋(ほんや)で 好(す)きな 雑誌(ざっし)を 買います。買い物は 夜(よる) 7時(しちじ)に 終(お)わります。","question":"この 人は どこで 雑誌を 買いますか。","furigana":"","choices":["本屋","スーパー","駅","レストラン"],"answer":0,"explanation":"Teks: 'それから本屋で好きな雑誌を買います'.","translation":"Belanja setiap Jumat. Sayur/daging di supermarket, majalah di toko buku. Selesai jam 7."}
]


def seed():
    print(f"Initializing DB at {os.environ['DB_PATH']} …")
    init_db()
    db = get_db()
    inserted = skipped = 0
    try:
        for q in QUESTIONS:
            exists = db.execute("SELECT id FROM questions WHERE id=?", (q["id"],)).fetchone()
            if exists:
                skipped += 1
                continue
            db.execute(
                """INSERT INTO questions
                   (id,section,level,instruction,passage,question,furigana,choices,answer,explanation,translation)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    q["id"], q["section"], q.get("level","N4"), q.get("instruction",""),
                    q.get("passage",""), q["question"], q.get("furigana",""),
                    json.dumps(q["choices"], ensure_ascii=False),
                    q["answer"], q.get("explanation",""), q.get("translation",""),
                ),
            )
            inserted += 1
        db.commit()
        print(f"Done. Inserted: {inserted}, Skipped (already exist): {skipped}")
        total = db.execute("SELECT COUNT(*) as c FROM questions").fetchone()["c"]
        print(f"Total questions in DB: {total}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
